
work_dir: ./ucla/bone_frame

# feeder
feeder: feeders.feeder_ucla.Feeder
test_feeder_args:
  data_path: bone
  window_size: 52

  label_path: val
  flag: frame
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6 # todo
  graph: graph.ucla.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 32
weights: ./ucla/bone_frame/weights/weights-35-11130.pt

save_score: True