
work_dir: ./ucla/bone_motion

# feeder
feeder: feeders.feeder_ucla.Feeder
train_feeder_args:
  data_path: bone motion
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
#  window_size: 300
  window_size: 52
  normalization: False
  flag: seq
  repeat: 5

test_feeder_args:
  data_path: bone motion
  window_size: 52

  label_path: val
  flag: seq
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ucla.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 50
device: [0]
batch_size: 16
forward_batch_size: 16
test_batch_size: 32
nesterov: True

## model
#model: model.ctrgcn.Model
#model_args:
#  num_class: 10
#  num_point: 20
#  num_person: 1
#  graph: graph.ucla.Graph
#  graph_args:
#    labeling_mode: 'spatial'
#
##optim
#weight_decay: 0.0001
#base_lr: 0.1
#lr_decay_rate: 0.1
#step: [50]
#
## training
#device: 0
#batch_size: 16
#test_batch_size: 64
#num_epoch: 65
#nesterov: True
#warm_up_epoch: 5
